### PR TITLE
Update Backup

### PR DESCRIPTION
**Pull request by 4dvn**
Separte the uboot and art to flash with programmer

### CODE REVIEW

**Comment by bruvv** [comment]
Can you elaborate this a bit more ?

**Comment by 4dvn** [comment]
> Can you elaborate this a bit more ?

This file help for flash the new winbond rom chip, i use some knowledge to split the backup.bin to ( art.bin ) config file and update the new u-boot file version ( uboot.bin )

**Comment by bruvv** [comment]
if you can fix the errors I can merge 👍

**Comment by bruvv** [comment]
last reminder or I will close it.

**Pull request closed without merging**
